a = input().lower()
# print("Аденин: " + str(a.count("а")))
# print("Гуанин: " + str(a.count("г")))
# print("Цитозин: " + str(a.count("ц")))
# print("Тимин: " + str(a.count("т")))
print(f"Аденин: {a.count('а')}")